"""RTSP video server — generates test pattern streams for each target camera.

Creates colour-bar test patterns using OpenCV and streams them via
ffmpeg piped to MediaMTX. Each target has 2 cameras (front/rear),
for a total of 20 RTSP streams.

Without ffmpeg/MediaMTX available, falls back to a status message.

Stream URLs: rtsp://localhost:8554/wints/T-XX/cam-front
             rtsp://localhost:8554/wints/T-XX/cam-rear
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
TOOLS_DIR = PROJECT_ROOT / "tools"


def _find_mediamtx() -> Path | None:
    """Locate the MediaMTX binary.

    Returns:
        Path to mediamtx executable, or None if not found.

    Example:
        >>> path = _find_mediamtx()
    """
    if sys.platform == "win32":
        candidate = TOOLS_DIR / "mediamtx" / "mediamtx.exe"
    else:
        candidate = TOOLS_DIR / "mediamtx" / "mediamtx"

    if candidate.exists():
        return candidate
    return None


def generate_mediamtx_config() -> str:
    """Generate a MediaMTX configuration file for WINTS test streams.

    Creates path entries for all 20 camera streams (10 targets × 2 cameras).
    Each stream accepts ffmpeg RTSP push and is accessible via RTSP pull.

    Returns:
        YAML configuration string for MediaMTX.

    Example:
        >>> config = generate_mediamtx_config()
        >>> 'T-01' in config
        True
    """
    lines = [
        "# MediaMTX Configuration — Auto-generated by WINTS",
        "# RTSP test pattern server for 10 targets × 2 cameras = 20 streams",
        "",
        "# General settings",
        "logLevel: info",
        "logDestinations: [stdout]",
        "",
        "# RTSP server",
        "rtsp: yes",
        "rtspAddress: :8554",
        "protocols: [tcp]",
        "",
        "# API",
        "api: yes",
        "apiAddress: :9997",
        "",
        "# Paths",
        "paths:",
    ]

    for i in range(1, 11):
        target_id = f"T-{i:02d}"
        for cam in ["cam-front", "cam-rear"]:
            lines.extend([
                f"  wints/{target_id}/{cam}:",
                '    source: publisher',
                '    sourceOnDemand: no',
                "",
            ])

    return "\n".join(lines)


def start_mediamtx() -> None:
    """Start MediaMTX RTSP server with WINTS configuration.

    If MediaMTX is not found, prints instructions for downloading it.

    Example:
        >>> start_mediamtx()  # Blocks until Ctrl+C
    """
    mediamtx = _find_mediamtx()
    if mediamtx is None:
        print("MediaMTX not found at tools/mediamtx/")
        print()
        print("Download from: https://github.com/bluenviron/mediamtx/releases")
        print(f"  - Extract mediamtx.exe to: {TOOLS_DIR / 'mediamtx' / 'mediamtx.exe'}")
        print()
        print("Or install via the WINTS setup:")
        print("  python -m scripts.wints setup")
        return

    # Generate config
    config_path = PROJECT_ROOT / "config" / "mediamtx.yml"
    config_content = generate_mediamtx_config()
    config_path.write_text(config_content, encoding="utf-8")
    print(f"MediaMTX config written to: {config_path}")

    # Start MediaMTX
    print(f"Starting MediaMTX from: {mediamtx}")
    print("RTSP streams available at: rtsp://localhost:8554/wints/T-XX/cam-front")
    print("Press Ctrl+C to stop")

    try:
        subprocess.run(
            [str(mediamtx), str(config_path)],
            cwd=str(TOOLS_DIR / "mediamtx"),
            check=True,
        )
    except KeyboardInterrupt:
        print("\nMediaMTX stopped.")
    except FileNotFoundError:
        print(f"Failed to execute: {mediamtx}")


if __name__ == "__main__":
    start_mediamtx()
